name: main ci process

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.INSTANCE_IP }}
          username: ${{ secrets.INSTANCE_USER }}
          key: ${{ secrets.INSTANCE_KEY }}
          port: ${{ secrets.INSTANCE_PORT }}
          script: |
            cd /home/ubuntu/mes-system
            git pull origin main
            pm2 delete mes-web
            npm i
            npm run build
            pm2 start npm --name "mes-web" -- run start
